#!/bin/sh
# Begin section update-alternatives
update-alternatives --install /etc/syslog.conf syslog-conf /etc/syslog.conf.busybox 50
# End section update-alternatives
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	systemctl $OPTS enable busybox-syslog.service

	if [ -z "$D" -a "enable" = "enable" ]; then
		systemctl --no-block restart busybox-syslog.service
	fi
fi
