#!/bin/sh
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	systemctl $OPTS enable var-volatile-lib.service var-volatile-cache.service var-volatile-spool.service var-volatile-srv.service

	if [ -z "$D" -a "enable" = "enable" ]; then
		systemctl --no-block restart var-volatile-lib.service var-volatile-cache.service var-volatile-spool.service var-volatile-srv.service
	fi
fi
